name: Supabase FPL Data Update

on:
  schedule:
    - cron: '00 9,11,13,15,19,21 * * *'

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: |
          pip install requests

      - name: Run FPL data update script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # Load Supabase URL from GitHub Secrets
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}  # Load Supabase API key from GitHub Secrets
        run: |
          python scripts/getPlayers.py
