name: Update Goalscorers each day

on:
  schedule:
    - cron: '00 14,17,19 * * 6'
    - cron: '00 2,16,19 * * 0'
    - cron: '00 2,22 * * 1,2,3,4,5'

jobs:
  run-fpl-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv pandas

    - name: Run FPL update script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python scripts/updateScorers.py
