name: Update Fixtures & Results

on:
  schedule:
    - cron: '00 14,17,19 * * 6'
    - cron: '00 16,19 * * 0'
    - cron: '00 22 * * *'

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script 
      run: |
        python scripts/getFixtures.py
